Repository praetorian-inc/noseyparker, pull requests merged in 2024-05, with the labels that each got.

#182 Fix the `--ignore-certs` option scoping
  CHANGELOG.md
  crates/noseyparker-cli/src/args.rs
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_datastore-2.snap
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_github-2.snap
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_github_repos-2.snap
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_github_repos_short-2.snap
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_github_short-2.snap
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_report-2.snap
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_report_short-2.snap
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_rules-2.snap
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_scan-2.snap
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_scan_short-2.snap
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_summarize-2.snap
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_summarize_short-2.snap
Labels: bug, ux

#183 Add support for colored backtraces; make tracing spans more useful
  Cargo.lock
  crates/noseyparker-cli/Cargo.toml
  crates/noseyparker-cli/src/cmd_scan.rs
  crates/noseyparker-cli/src/main.rs
Labels: enhancement, ux

#187 Adding a rule for Databricks Personal Access Token detection
  CHANGELOG.md
  crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_check_builtins-2.snap
  crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_json-2.snap
  crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_noargs-2.snap
  crates/noseyparker/data/default/builtin/rules/databricks.yml
  crates/noseyparker/data/default/builtin/rulesets/default.yml
Labels: enhancement, detection

#188 Update dependencies
  Cargo.lock
  crates/input-enumerator/Cargo.toml
  crates/noseyparker-digest/Cargo.toml
  crates/noseyparker/Cargo.toml
Labels: techdebt

#190 Add a new rule for combined AWS API key and secret
  CHANGELOG.md
  crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_check_builtins-2.snap
  crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_json-2.snap
  crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_noargs-2.snap
  crates/noseyparker-cli/tests/scan/appmaker/mod.rs
  crates/noseyparker-cli/tests/scan/appmaker/snapshots/test_noseyparker__scan__appmaker__scan_workflow_from_git_url-2.snap
  crates/noseyparker-cli/tests/scan/appmaker/snapshots/test_noseyparker__scan__appmaker__scan_workflow_from_git_url-4.snap
  crates/noseyparker-cli/tests/scan/appmaker/snapshots/test_noseyparker__scan__appmaker__scan_workflow_from_git_url-5.snap
  crates/noseyparker/data/default/builtin/rules/aws.yml
  crates/noseyparker/data/default/builtin/rulesets/default.yml
Labels: enhancement, detection
