Repository praetorian-inc/noseyparker, pull requests merged in 2024-06, with the labels that each got.

#191 Strip releases; include separate minimal debug info
  Cargo.toml
  Dockerfile.alpine
  scripts/create-release.zsh
Labels: enhancement, packaging

#192 Add a new rule for base64-pem-encoded private keys
  CHANGELOG.md
  README.md
  crates/noseyparker-cli/src/cmd_scan.rs
  crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_check_builtins-2.snap
  crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_json-2.snap
  crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_noargs-2.snap
  crates/noseyparker/data/default/builtin/rules/pem.yml
  crates/noseyparker/data/default/builtin/rulesets/default.yml
Labels: enhancement, detection

#193 Add additional rules
  CHANGELOG.md
  README.md
  crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_check_builtins-2.snap
  crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_json-2.snap
  crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_noargs-2.snap
  crates/noseyparker-cli/tests/scan/appmaker/snapshots/test_noseyparker__scan__appmaker__scan_workflow_from_git_url-4.snap
  crates/noseyparker/data/default/builtin/rules/aws.yml
  crates/noseyparker/data/default/builtin/rules/azure.yml
  crates/noseyparker/data/default/builtin/rules/google.yml
  crates/noseyparker/data/default/builtin/rulesets/default.yml
Labels: enhancement, detection

#194 General support - PATs in git password field
  crates/noseyparker/src/git_binary.rs
Labels: enhancement, integration

#196 Improve `summarize`
  CHANGELOG.md
  crates/noseyparker-cli/src/args.rs
  crates/noseyparker-cli/src/cmd_scan.rs
  crates/noseyparker-cli/src/cmd_summarize.rs
  crates/noseyparker-cli/tests/datastore/snapshots/test_noseyparker__datastore__export_empty-2.snap
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_summarize-2.snap
  crates/noseyparker-cli/tests/scan/appmaker/snapshots/test_noseyparker__scan__appmaker__scan_workflow_from_git_url-2.snap
  crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__scan_secrets1-2.snap
  crates/noseyparker-cli/tests/scan/snippet_length/snapshots/test_noseyparker__scan__snippet_length__scan_changing_snippet_length-2.snap
  crates/noseyparker-cli/tests/scan/snippet_length/snapshots/test_noseyparker__scan__snippet_length__scan_changing_snippet_length-9.snap
  crates/noseyparker/src/datastore.rs
  crates/noseyparker/src/datastore/finding_summary.rs
Labels: enhancement, reporting, ux

#197 Use new Linux arm64 runners in CI
  .github/workflows/ci.yml
  .github/workflows/release-artifacts.yml
Labels: enhancement, testing, packaging

#198 Update dependencies with `cargo update`
  Cargo.lock
Labels: techdebt

#199 Prepare for v0.18.0 release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__version_long-2.snap
Labels: packaging
